### ISSUE TITLE
CircleCIでのビルドに失敗する

### ISSUE THREAD

**Issue by circularuins** [mtburn/MTBurn-Android-SDK-Install-Guide#7]
以下、該当エラーメッセージ

> Configuring > 1/3 projects > :app > Compiling script into cache2/3 projects > :mTBurnAndroidSDKRelease > Compiling script into > Compiling script into3/3 projects
> Configuring > 3/3 projectsFAILURE: 
> Configuring > 3/3 projectsBuild failed with an exception.
> Configuring > 3/3 projects
> Configuring > 3/3 projects
> Configuring > 3/3 projects* What went wrong:
> Configuring > 3/3 projectsA problem occurred configuring project ':app'.
> Configuring > 3/3 projects> 
> Configuring > 3/3 projectsA problem occurred configuring project ':mTBurnAndroidSDKRelease'.
> Configuring > 3/3 projects   
> Configuring > 3/3 projects> 
> Configuring > 3/3 projectsfailed to find Build Tools revision 19.1.0
> Configuring > 3/3 projects
> Configuring > 3/3 projects* Try:
> Configuring > 3/3 projectsRun with 
> Configuring > 3/3 projects--stacktrace
> Configuring > 3/3 projects option to get the stack trace. Run with 
> Configuring > 3/3 projects--info
> Configuring > 3/3 projects or 
> Configuring > 3/3 projects--debug
> Configuring > 3/3 projects option to get more log output.
> Configuring > 3/3 projects
> Configuring > 3/3 projectsBUILD FAILED

**Comment by circularuins** [comment]
![image](https://cloud.githubusercontent.com/assets/1131119/11735031/09cc8ad6-a000-11e5-9e4b-5c935e7a4424.png)

**Comment by circularuins** [comment]
builtoolsがないというのは、circleCIの環境の中での話でしょうか？
ローカル環境のプロジェクト設定では19.1インストール済みとなっているのですが、それは関係ない話になりますか？

**Comment by yoheimuta** [comment]
お手数おかけしております。上記確認致します。

**Comment by yoheimuta** [comment]
> builtoolsがないというのは、circleCIの環境の中での話でしょうか？

はい。ローカル環境とは関係ないのではと思ってます。

例えば、https://github.com/infinum/Productive-Android-app/blob/7e9c356301ba1c7ac4ef3c6c11675c11c58e9f9a/circle.yml#L11 （適当なプロジェクトを拾ってます）のような行が該当する部分ではと思ってます。ただ、こちらでは再現できていないので、確信があるわけではありません。

よろしくお願いします。

**Comment by circularuins** [comment]
アドバイス通りcircleCI側で19.1を入れたところ無事ビルドに成功しました。
ありがとうございました！
